language: php
dist: xenial

sudo: required

addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.2

env:
  - DB=pgsql MOODLE_BRANCH=master

before_install:
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
  - sudo service postgresql stop
  - sudo mv /var/lib/postgresql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/postgresql /var/lib/postgresql
  - sudo service postgresql start 9.6
  - nvm install 8.9
  - nvm use 8.9
  - cp config-dist.php config.php
  - mkdir -p "$HOME"/roots/base
  - sed -i -e "s%= 'moodle'%= 'travis_ci_test'%" -e "s%= 'password'%= ''%" config.php
  - sed -i -e "s%http://example.com/moodle%https://localhost%" -e "s%/home/example/moodledata%/home/travis/roots/base%" config.php
  - sed -i -e "s%= 'username'%= 'postgres'%" config.php
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - mkdir -p "$HOME"/roots/phpunit
  - sed -i -e "/require_once/i \\\$CFG->phpunit_dataroot = '\/home\/travis\/roots\/phpunit';" -e "/require_once/i \\\$CFG->phpunit_prefix = 'p_';" config.php

install:
  - php admin/tool/phpunit/cli/init.php
  - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs

script:
  - vendor/bin/phpunit --coverage-text  --coverage-clover build/logs/clover.xml --configuration mod/forum

after_success:
  - travis_retry vendor/bin/php-coveralls