language: php
dist: xenial

sudo: required

addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.2

env:
  - DB=pgsql MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
  - cd build/moodle
  - php admin/tool/phpunit/cli/init.php
  - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
 
script:
  - vendor/bin/phpunit --coverage-text  --coverage-clover build/logs/clover.xml --configuration mod/forum

after_success:
  - php vendor/bin/coveralls -v
